"""
snRNAseq_spatial_integrate.py

Purpose
-------
This script integrates adult human frontal-lobe single-nucleus RNA-seq (snRNA-seq)
data with frontal-lobe spatial transcriptomics data. It uses shared genes between
both modalities, performs normalization and scaling, applies Harmony integration,
and then projects snRNA-seq cell-type labels onto spatial cells/spots using a
nearest-neighbor voting strategy in the integrated UMAP space.

The script also performs a simple expression imputation step: for each spatial
cell/spot, it averages the raw expression profiles of its nearest snRNA-seq
neighbors and writes the imputed spatial expression matrix to an AnnData file.

Expected inputs
---------------
1. ./save_data/FL_s1_obje.h5ad
   - Raw spatial AnnData object for the frontal lobe sample.
   - Must contain the raw gene expression matrix and gene metadata.

2. ./save_data/FL_stagate_v0.h5ad
   - Processed spatial AnnData object after STAGATE or related spatial embedding.
   - Must contain the same spatial cell/spot names as a subset of FL_s1_obje.h5ad.
   - Expected to include embeddings such as t-SNE/UMAP and metadata such as mclust.

3. ./data/adata_clusters2_noraw_v1.h5ad
   - Processed snRNA-seq AnnData object with cell metadata and dimensional reductions.
   - Must contain obs columns including MainLoc and clusters2_v1.

4. ./data/adata_clusters2_raw.h5ad
   - Raw snRNA-seq AnnData object containing the expression matrix used for imputation.
   - Must have cells aligned to the processed snRNA-seq object.

Expected outputs
----------------
1. A visualization of the frontal-lobe snRNA-seq UMAP colored by clusters2_v1.
2. A joint UMAP of spatial and snRNA-seq cells after Harmony integration.
3. Per-cell/per-spot predicted spatial cell-type labels stored in:
   adata_FL_st.obs['Predict_cell_type']
4. ./save_data/FL_st_imputation.h5ad
   - Spatial AnnData object containing imputed expression values.

Important notes
---------------
- The script assumes that genes can be matched using adata.var.index after setting
  the spatial var index to the 'features' column.
- The label-transfer step uses UMAP coordinates, which are useful for visualization
  but may not be the most stable representation for quantitative nearest-neighbor
  prediction. For fully reproducible analyses, consider using X_pca_harmony or
  another integrated latent space for nearest-neighbor search.
- This script is written as an executable analysis script rather than a function-based
  package. Paths may need to be adjusted depending on the local repository structure.
"""

# -----------------------------
# 1. Import required packages
# -----------------------------

# Standard library imports. These are useful for system/path checks if the script
# is later expanded into a command-line workflow.
import os
import sys

# Scanpy is used for AnnData handling, preprocessing, PCA, neighborhood graph
# construction, UMAP calculation, and plotting.
import scanpy as sc

# scanpy.external provides wrappers for external integration methods. Here we use
# Harmony to remove modality/technology effects between snRNA-seq and spatial data.
import scanpy.external as sce

# pandas and numpy are used for table manipulation and numerical operations.
import pandas as pd
import numpy as np

# seaborn is imported for potential downstream visualization; this script mainly
# uses matplotlib and Scanpy plotting functions.
import seaborn as sns
import matplotlib.pyplot as plt

# NearestNeighbors is used for two related tasks:
#   1. assigning snRNA-seq cell-type labels to spatial cells/spots;
#   2. imputing spatial expression using neighboring snRNA-seq profiles.
from sklearn.neighbors import NearestNeighbors

# tqdm is imported for progress bars. The current script prints chunk progress
# manually, but tqdm can be used if the imputation loop is further refined.
from tqdm import tqdm


# -----------------------------
# 2. Load spatial transcriptomics data
# -----------------------------

# Load the raw spatial AnnData object. This object is expected to contain the raw
# expression matrix for the frontal-lobe spatial sample.
adata_FL_raw = sc.read("./save_data/FL_s1_obje.h5ad")

# Load the processed spatial AnnData object. This object is expected to contain
# processed cell/spot-level metadata and embeddings generated by STAGATE or another
# spatial analysis workflow.
adata_FL = sc.read('./save_data/FL_stagate_v0.h5ad')

# Reconstruct a spatial AnnData object that combines:
#   - raw expression values from adata_FL_raw;
#   - processed metadata and embeddings from adata_FL.
#
# adata_FL.obs_names are used to select and order the same cells/spots from the raw
# spatial object. This step assumes that every obs_name in adata_FL is present in
# adata_FL_raw.
adata_FL_st = sc.AnnData(
    X=adata_FL_raw[adata_FL.obs_names, :].X,
    obs=adata_FL.obs,
    var=adata_FL_raw.var,
    uns=adata_FL.uns,
    obsm=adata_FL.obsm,
    varm=adata_FL.varm,
    obsp=adata_FL.obsp,
)

# Use the 'features' column as the gene index for the spatial AnnData object.
# This is important because the next steps identify shared genes between the
# spatial data and the snRNA-seq data by intersecting var.index.
#
# Potential issue to check:
#   adata_FL_st.var must contain a column named 'features'. If not, this line will
#   fail and the correct gene-name column should be substituted.
adata_FL_st.var = adata_FL_st.var.set_index('features')


# -----------------------------
# 3. Load adult cortex snRNA-seq data
# -----------------------------

# Load the processed snRNA-seq AnnData object. This object is expected to contain
# curated metadata, cell-type annotations, and low-dimensional embeddings.
adata = sc.read('./data/adata_clusters2_noraw_v1.h5ad')

# Load the corresponding raw snRNA-seq AnnData object. This is used to recover the
# raw expression matrix for imputation while keeping processed metadata from adata.
adata_raw = sc.read('./data/adata_clusters2_raw.h5ad')

# Reconstruct a single-cell AnnData object that combines:
#   - raw snRNA-seq expression from adata_raw;
#   - processed metadata and embeddings from adata;
#   - gene metadata from adata_raw.
#
# This assumes that adata and adata_raw contain cells in the same order. If the
# order differs, cells should be explicitly aligned by obs_names before creating
# this object.
adata_FL_sc = sc.AnnData(
    X=adata_raw.X,
    obs=adata.obs,
    var=adata_raw.var,
    uns=adata.uns,
    obsm=adata.obsm,
    varm=adata_raw.varm,
    obsp=adata.obsp,
)


# -----------------------------
# 4. Select frontal-lobe snRNA-seq cells
# -----------------------------

# Keep only snRNA-seq nuclei annotated as frontal lobe. This makes the reference
# data anatomically matched to the frontal-lobe spatial transcriptomics sample.
#
# Required metadata:
#   adata_FL_sc.obs['MainLoc'] must exist and contain the value 'Frontal lobe'.
adata_FL_sc = adata_FL_sc[adata_FL_sc.obs['MainLoc'] == 'Frontal lobe']

# Visualize the frontal-lobe snRNA-seq reference UMAP using the curated cluster
# labels. This is a quality-control plot to inspect whether the expected cell
# populations are present in the reference.
#
# Required metadata:
#   adata_FL_sc.obs['clusters2_v1'] must contain the cell-type/subclass labels.
sc.pl.umap(adata_FL_sc, color='clusters2_v1', frameon=False, title='')

# Work on a copy of the frontal-lobe snRNA-seq object for the integration workflow.
adata_sc = adata_FL_sc.copy()


# -----------------------------
# 5. Match shared genes between spatial and snRNA-seq data
# -----------------------------

# Identify genes shared by the spatial and snRNA-seq AnnData objects. Only these
# shared genes are used for cross-modality integration.
list_of_variable_names = adata_FL_st.var.index.intersection(adata_sc.var.index)

# Subset the spatial object to the shared genes.
adata_subset = adata_FL_st[:, list_of_variable_names]

# Recompute the intersection from the opposite direction and subset the snRNA-seq
# object. This produces a gene-matched single-cell reference object.
list_of_variable_names = adata_sc.var.index.intersection(adata_FL_st.var.index)
adata_sc_subset = adata_sc[:, list_of_variable_names]

# Note:
# The two objects should now contain the same gene set. For complete reproducibility,
# users may add an explicit check such as:
#   assert list(adata_subset.var_names) == list(adata_sc_subset.var_names)
# If the order differs, reorder one object before concatenation.


# -----------------------------
# 6. Normalize and scale snRNA-seq data
# -----------------------------

# Normalize each snRNA-seq cell to the same total count depth.
sc.pp.normalize_total(adata_sc_subset)

# Log-transform normalized counts using log(1 + x), which is standard for Scanpy
# preprocessing prior to PCA.
sc.pp.log1p(adata_sc_subset)

# Compute quality-control metrics. total_counts is later used as a covariate for
# regression.
sc.pp.calculate_qc_metrics(adata_sc_subset, percent_top=None, inplace=True)

# Regress out total sequencing depth to reduce technical effects.
sc.pp.regress_out(adata_sc_subset, ['total_counts'])

# Scale each gene to unit variance and zero mean. This is required before PCA.
sc.pp.scale(adata_sc_subset)


# -----------------------------
# 7. Normalize and scale spatial transcriptomics data
# -----------------------------

# Apply the same preprocessing steps to the spatial data so the two modalities are
# more comparable before integration.
sc.pp.normalize_total(adata_subset)
sc.pp.log1p(adata_subset)
sc.pp.calculate_qc_metrics(adata_subset, percent_top=None, inplace=True)
sc.pp.regress_out(adata_subset, ['total_counts'])
sc.pp.scale(adata_subset)


# -----------------------------
# 8. Add modality labels and concatenate datasets
# -----------------------------

# Add a technology label to each object. Harmony will use this label to align the
# two technologies while preserving biological variation.
adata_subset.obs['tech'] = 'st_FL'
adata_sc_subset.obs['tech'] = 'sc_FL'

# Concatenate spatial and snRNA-seq data into one AnnData object.
#
# batch_key='dataset' creates a new obs column indicating the data source:
#   - 'st' for spatial transcriptomics;
#   - 'scrna' for snRNA-seq.
combine_adata = adata_subset.concatenate(
    adata_sc_subset,
    batch_key='dataset',
    batch_categories=['st', 'scrna'],
)


# -----------------------------
# 9. PCA and Harmony integration
# -----------------------------

# Number of principal components used for cross-modality integration.
npc = 30

# Compute PCA on the concatenated dataset.
sc.tl.pca(combine_adata, n_comps=npc)

# Run Harmony integration using the 'tech' column to correct modality-specific
# effects. Harmony stores the corrected embedding in combine_adata.obsm['X_pca_harmony'].
sce.pp.harmony_integrate(combine_adata, 'tech')
print('Harmony integration finished')


# -----------------------------
# 10. Construct neighborhood graph and UMAP
# -----------------------------

# Build a nearest-neighbor graph using the Harmony-corrected PCA representation.
sc.pp.neighbors(combine_adata, n_neighbors=20, use_rep='X_pca_harmony')

# Compute a UMAP embedding from the integrated neighborhood graph.
sc.tl.umap(combine_adata)

# Plot the integrated UMAP colored by dataset and cell-type labels. Spatial cells
# will not necessarily have clusters2_v1 unless that metadata was already present
# or introduced during concatenation.
sc.pl.umap(
    combine_adata,
    color=['dataset', 'clusters2_v1'],
    legend_loc='right margin',
    frameon=False,
)


# -----------------------------
# 11. Split integrated object into spatial query and snRNA-seq reference
# -----------------------------

# Spatial query cells/spots after integration.
combine_adata_st = combine_adata[combine_adata.obs['dataset'] == 'st'].copy()

# snRNA-seq reference cells after integration.
combine_adata_sc = combine_adata[combine_adata.obs['dataset'] == 'scrna'].copy()


# -----------------------------
# 12. Transfer snRNA-seq cell-type labels to spatial cells/spots
# -----------------------------

# Number of snRNA-seq neighbors used for majority-vote label transfer.
n_neighbors = 20

# Fit a nearest-neighbor model on snRNA-seq cells in the integrated UMAP space.
#
# Note:
# UMAP is convenient but stochastic and optimized for visualization. For a more
# robust label-transfer workflow, consider fitting neighbors on X_pca_harmony.
neigh = NearestNeighbors(n_neighbors=n_neighbors, algorithm='auto').fit(
    combine_adata_sc.obsm['X_umap']
)

# For each spatial cell/spot, retrieve the nearest snRNA-seq reference cells.
distances, indices = neigh.kneighbors(combine_adata_st.obsm['X_umap'])

# Flatten all neighbor indices. This vector is reused later for expression imputation.
indices_all = np.concatenate(indices)

# Convert neighbor indices to snRNA-seq cluster labels.
#
# The resulting data frame has:
#   - one row per spatial cell/spot;
#   - one column per nearest snRNA-seq neighbor;
#   - values equal to the neighbor cell-type labels.
df = pd.DataFrame(np.take(list(adata_FL_sc.obs.clusters2_v1), indices))

# Assign spatial cell/spot names as the row index so predictions can be merged back
# into adata_FL_st.obs.
df.index = adata_FL_st.obs_names


def max_occurrence(row):
    """Return the most frequent label among the nearest-neighbor labels.

    Parameters
    ----------
    row : pandas.Series
        The cell-type labels of the nearest snRNA-seq neighbors for one spatial
        cell/spot.

    Returns
    -------
    str
        The majority-vote cell-type label. If there is a tie, pandas returns the
        first label among the tied values after value_counts ordering.
    """
    return row.value_counts().idxmax()


# Apply majority voting across each row of neighbor labels.
max_elements = df.apply(max_occurrence, axis=1)

# Store the predictions in a one-column data frame.
new_df = pd.DataFrame(max_elements, columns=['Predict_cell_type'])

# Add predicted cell-type labels to the spatial AnnData object.
adata_FL_st.obs['Predict_cell_type'] = new_df['Predict_cell_type'].astype('category')


# -----------------------------
# 13. Visualize predicted spatial cell types
# -----------------------------

# Retrieve all predicted cell-type categories.
clusters = adata_FL_st.obs['Predict_cell_type'].cat.categories

# Create a 4-by-6 grid of axes. This assumes up to 24 cell types. If the number of
# predicted categories is larger than 24, increase the grid size to avoid index errors.
fig, axes = plt.subplots(4, 6, figsize=(20, 14))

# For each predicted cell type, plot the full spatial t-SNE background using mclust
# and overlay the cells/spots assigned to the current predicted label.
#
# Required fields:
#   - adata_FL_st.obsm['X_tsne'] or equivalent t-SNE coordinates used by sc.pl.tsne;
#   - adata_FL_st.obs['mclust'];
#   - adata_FL_st.obs['Predict_cell_type'].
for i, cluster in enumerate(clusters):
    ax = axes[i // 6, i % 6]
    sc.pl.tsne(
        adata_FL_st,
        color=['mclust'],
        groups='',
        ax=ax,
        size=2,
        show=False,
        frameon=False,
        title=cluster,
        legend_loc='',
    )
    sc.pl.tsne(
        adata_FL_st,
        color=['Predict_cell_type'],
        groups=[cluster],
        ax=ax,
        size=2,
        show=False,
        frameon=False,
        title=cluster,
        legend_loc='',
    )


# -----------------------------
# 14. Impute spatial expression from nearest snRNA-seq neighbors
# -----------------------------

print("Preparing for imputation...")

# Recreate spatial and snRNA-seq subsets from the integrated AnnData object.
combine_adata_st = combine_adata[combine_adata.obs['dataset'] == 'st'].copy()
combine_adata_sc = combine_adata[combine_adata.obs['dataset'] == 'scrna'].copy()

# Use the original frontal-lobe snRNA-seq object for raw expression imputation.
adata_sc_imputation = adata_sc.copy()

# Extract the snRNA-seq expression matrix. This matrix should contain genes to be
# imputed into the spatial cells/spots. It can be dense or sparse depending on how
# the input AnnData object was saved.
singlecell_rawexpr = adata_sc_imputation.X

# Number of genes/features in the snRNA-seq expression matrix.
shape1 = singlecell_rawexpr.shape[1]

# Repeat nearest-neighbor search for imputation. This uses the same UMAP-space
# neighbor strategy as label transfer.
n_neighbors = 20
neigh = NearestNeighbors(n_neighbors=n_neighbors, algorithm='auto').fit(
    combine_adata_sc.obsm['X_umap']
)
distances, indices = neigh.kneighbors(combine_adata_st.obsm['X_umap'])
indices_all = np.concatenate(indices)

# For each spatial cell/spot, retrieve expression values from its nearest snRNA-seq
# neighbors and average the expression across neighbors. The loop processes cells
# in chunks to reduce peak memory use.
adata_st_imputation = []
for i in range(0, indices_all.shape[0], 100000):
    print(f'Processing indices from {i} to {i + 100000}')

    # Extract the raw expression profiles for a chunk of neighbor cells.
    test1 = singlecell_rawexpr[indices_all[i:i + 100000]]

    # Reshape the chunk into:
    #   number_of_spatial_cells_in_chunk x n_neighbors x number_of_genes
    # This works because indices_all was created by flattening the 2D neighbor index
    # array row-wise.
    test2 = test1.reshape(-1, n_neighbors, shape1)

    # Average expression across the n_neighbors reference cells to obtain one
    # imputed expression vector per spatial cell/spot.
    test3 = np.mean(test2, axis=1)

    # Store the imputed expression block.
    adata_st_imputation.append(test3)

# Concatenate all imputed expression blocks into a complete spatial expression matrix.
adata_imput_expr = np.concatenate(adata_st_imputation, axis=0)


# -----------------------------
# 15. Save imputed spatial AnnData object
# -----------------------------

# Create an AnnData object for the imputed spatial expression matrix. The spatial
# metadata and embeddings are copied from adata_FL_st so the imputed expression can
# be visualized or analyzed together with existing spatial annotations.
adata_st_imput = sc.AnnData(
    X=adata_imput_expr,
    obs=adata_FL_st.obs,
    uns=adata_FL_st.uns,
    obsm=adata_FL_st.obsm,
)

# Use snRNA-seq gene names as the imputed gene names.
adata_st_imput.var_names = adata_sc.var_names

# Write the imputed spatial AnnData object to disk.
adata_st_imput.write('./save_data/FL_st_imputation.h5ad')
