"""
1.1_preprocess_scanpy.py

Purpose
-------
Preprocess aggregated adult human cortex single-nucleus RNA-seq data generated by
Cell Ranger. This script performs sample metadata merging, basic quality control,
doublet removal with Scrublet, normalization, highly variable gene selection,
batch-aware neighborhood construction with BBKNN, UMAP visualization, Leiden
clustering, and metadata export for downstream Seurat-based annotation.

Main inputs
-----------
- ./Data/adult_human_cortex/AHCaggr24/filtered_feature_bc_matrix/
  Cell Ranger filtered feature-barcode matrix from the aggregated dataset.
- ./Data/sample_info_v1.csv
  Sample-level metadata. It must contain a `number` column matching the numeric
  batch suffix in 10x barcode names and should include columns such as sample,
  donor, location, and MainLoc used downstream.

Main outputs
------------
- ./Data/raw_v1.h5ad
  Raw AnnData object after Cell Ranger loading and sample metadata merging.
- ./Data/HC_HVG2000_v1.h5ad
  Processed AnnData object after QC, doublet filtering, normalization, HVG
  selection, BBKNN, UMAP, and Leiden clustering.
- ./Data/HC_HVG2000_filt_lowQualityCluster.h5ad
  Processed object after removing manually identified low-quality Leiden clusters.
- ./Data/HC_HVG2000_metadata.csv
  Cell-level metadata exported for Seurat annotation in script 1.2.
"""

# Core single-cell and numerical libraries.
import scanpy as sc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# BBKNN is used to construct a batch-corrected neighbor graph before UMAP/clustering.
from bbknn import bbknn

# Scrublet is used to identify likely doublets within each sample/batch.
import scrublet as scr

# Print Python executable and version to make the computational environment traceable.
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)

# Set default resolution for Scanpy-generated figures.
sc.settings.set_figure_params(dpi=150)

# -----------------------------------------------------------------------------
# Step 1. Load Cell Ranger matrix and attach sample-level metadata
# -----------------------------------------------------------------------------

# Read the 10x Genomics mtx directory. Gene and barcode information are taken
# from the Cell Ranger `filtered_feature_bc_matrix` folder.
adata = sc.read_10x_mtx(
    './Data/adult_human_cortex/AHCaggr24/filtered_feature_bc_matrix/',
    cache=False
)

# Identify mitochondrial genes. In human 10x data, mitochondrial gene symbols
# usually start with "MT-".
mito_genes = adata.var_names.str.startswith('MT-')

# Calculate the fraction of mitochondrial UMIs per nucleus/cell. This is a QC
# metric: nuclei/cells with high mitochondrial fraction are often damaged or low
# quality. `.A1` converts the sparse matrix result to a one-dimensional array.
adata.obs['percent_mito'] = (
    np.sum(adata[:, mito_genes].X, axis=1).A1 / np.sum(adata.X, axis=1).A1
)

# Calculate total UMI counts per nucleus/cell.
adata.obs['n_counts'] = adata.X.sum(axis=1).A1

# Read sample metadata. The `number` column is expected to match the 10x barcode
# suffix created during Cell Ranger aggregation, e.g. AAAC...-1, AAAC...-2, etc.
info = pd.read_csv("./Data/sample_info_v1.csv")

# Preserve the original cell barcode as a metadata column before merging.
adata.obs['cell'] = adata.obs.index

# Split aggregated 10x barcodes into raw barcode and batch suffix. For example,
# `AAACCCAAG...-12` becomes barcode=`AAACCCAAG...`, batch=`12`.
adata.obs[['barcode', 'batch']] = adata.obs['cell'].str.split('-', expand=True)
adata.obs['batch'] = pd.to_numeric(adata.obs['batch'])

# Merge cell-level QC metadata with sample-level annotations. The final index is
# reset to the original cell barcode stored in `cell`.
adata.obs = adata.obs.merge(info, left_on='batch', right_on='number').set_index('cell')

# Save a raw annotated object before filtering. This is useful for debugging and
# for reproducing later filtering decisions.
adata.write("./Data/raw_v1.h5ad")

# Plot the distribution of total counts before filtering.
sc.pl.violin(adata, ['n_counts'], jitter=0.4, multi_panel=False)

# -----------------------------------------------------------------------------
# Step 2. Basic QC filtering and doublet removal
# -----------------------------------------------------------------------------

# Keep cells/nuclei with at least 200 detected genes.
sc.pp.filter_cells(adata, min_genes=200)

# Keep genes detected in at least 10 cells/nuclei.
sc.pp.filter_genes(adata, min_cells=10)

# Apply additional QC thresholds:
# - n_genes between 600 and 10,000
# - percent_mito < 0.2, i.e. mitochondrial fraction below 20%
# These thresholds should be reported in Methods and can be adjusted if needed.
adata = adata[
    (adata.obs['n_genes'].between(600, 10000)) &
    (adata.obs['percent_mito'] < 0.2)
]


def run_scrublet(batch_str):
    """Run Scrublet doublet detection for one batch/sample.

    Parameters
    ----------
    batch_str : int or str
        Batch/sample identifier stored in `adata.obs['batch']`.

    Returns
    -------
    pandas.Index
        Cell barcodes predicted as doublets in this batch.
    """
    # Subset cells belonging to the current batch. Doublet detection is run per
    # batch because doublet score distributions can differ across samples.
    raw_filt = adata[adata.obs.batch == batch_str, :]

    # Initialize Scrublet on the raw count matrix of this batch. The expected
    # doublet rate is set to 10%; modify this value if platform/loading estimates
    # indicate a different expected rate.
    scrub = scr.Scrublet(raw_filt.X, expected_doublet_rate=0.1)

    # Calculate doublet scores and binary doublet calls.
    doublet_scores, predicted_doublets = scrub.scrub_doublets()

    # Return cell IDs predicted as doublets.
    return raw_filt.obs.index[predicted_doublets]


# Create a copy of metadata to store doublet labels without altering the object
# during the per-batch loop.
df_cell = adata.obs.copy()
df_cell['doublet'] = 'false'

# Run Scrublet independently for every batch and mark predicted doublets.
for batch in adata.obs['batch'].unique():
    filt_cell = run_scrublet(batch)
    df_cell.loc[filt_cell, 'doublet'] = 'true'
    print(f"Batch finished: {batch}")

# Add doublet annotations to the AnnData object and remove predicted doublets.
adata.obs['doublet'] = df_cell['doublet']
adata = adata[adata.obs.doublet == 'false']

# -----------------------------------------------------------------------------
# Step 3. Normalization, HVG selection, dimensionality reduction, and clustering
# -----------------------------------------------------------------------------

# Normalize each cell to the same total count depth, then log-transform counts.
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)

# Store the normalized/log-transformed full gene matrix before restricting to HVGs.
adata.raw = adata

# Select the top 2,000 highly variable genes for dimensionality reduction.
sc.pp.highly_variable_genes(adata, n_top_genes=2000)
adata = adata[:, adata.var['highly_variable']]

# Regress out total counts and mitochondrial fraction, then scale expression.
sc.pp.regress_out(adata, ['n_counts', 'percent_mito'])
sc.pp.scale(adata, max_value=10)

# Run PCA using 100 components.
sc.tl.pca(adata, svd_solver='arpack', n_comps=100)

# Plot variance explained to justify the number of PCs used downstream.
sc.pl.pca_variance_ratio(adata, log=True, n_pcs=100)

# Construct a batch-corrected neighbor graph using BBKNN. The `sample` metadata
# column should come from `sample_info_v1.csv` and indicates the sample/donor used
# for batch-aware neighborhood correction.
bbknn(adata, batch_key='sample', n_pcs=80)

# Compute UMAP based on the BBKNN graph and perform Leiden clustering.
sc.tl.umap(adata)
sc.tl.leiden(adata, resolution=1)

# Identify marker genes for Leiden clusters using Wilcoxon rank-sum test.
sc.tl.rank_genes_groups(adata, 'leiden', method='wilcoxon')

# Save processed object and generate QC/clustering UMAPs.
adata.write("./Data/HC_HVG2000_v1.h5ad")
sc.pl.umap(adata, color=['percent_mito', 'n_genes'], legend_loc='on data')
sc.pl.umap(adata, color='leiden', legend_loc='on data')

# -----------------------------------------------------------------------------
# Step 4. Remove manually identified low-quality clusters and export metadata
# -----------------------------------------------------------------------------

# Remove Leiden clusters 17 and 5, which were manually identified as low-quality
# clusters based on QC metrics and/or marker inspection.
adata = adata[~adata.obs.leiden.isin(['17', '5'])]

# Recalculate UMAP and Leiden clustering after filtering low-quality clusters.
# Note: the BBKNN neighbor graph is inherited from the previous object. For a fully
# fresh analysis, rerun BBKNN before UMAP/clustering.
sc.tl.umap(adata)
sc.tl.leiden(adata, resolution=1)

# Save the final filtered AnnData object and export metadata for Seurat workflow.
adata.write("./Data/HC_HVG2000_filt_lowQualityCluster.h5ad")
adata.obs.to_csv('./Data/HC_HVG2000_metadata.csv')
