# 1.2_process_annotate_seurat.r
#
# Purpose:
#   Import adult human cortex single-nucleus RNA-seq counts into Seurat, attach
#   Scanpy-derived metadata, integrate samples across cortical locations, perform
#   clustering, annotate major neuronal and non-neuronal classes, and save the
#   final integrated Seurat object for downstream analyses.
#
# Input:
#   ~/PythonScripts/Adult_cortical/Data/adult_human_cortex/AHCaggr24/filtered_feature_bc_matrix/
#     Cell Ranger filtered feature-barcode matrix.
#   ./Data/HC_HVG2000_metadata.csv
#     Metadata generated by 1.1_preprocess_scanpy.py.
#   ./Data/color.rds
#     Color palette used in UMAP plots.
#
# Output:
#   ./data/All_region_cortex_seurat_Exc.rds
#     Excitatory neuron subset with subclass/subcluster annotations.
#   ./data/All_region_cortex_seurat_v1.rds
#     Final integrated and annotated Seurat object.
#
# Notes:
#   This script shows the complete excitatory-neuron annotation section and uses
#   placeholders for analogous inhibitory-neuron and non-neuronal workflows. The
#   final metadata merge expects `ch.In`, `ch.Nn`, and `ch.integrated.sub.sub` to
#   have been generated by the corresponding annotation steps.

# Load libraries for single-cell analysis, matrix handling, plotting, and data I/O.
library(batchelor)
library(Seurat)
library(Matrix)
library(matrixStats)
library(dplyr)
library(ggplot2)
library(SeuratDisk)

# -----------------------------------------------------------------------------
# Step 1. Load raw counts and Scanpy-derived metadata
# -----------------------------------------------------------------------------

# Load a custom color palette used for cluster visualization.
cls100 <- readRDS('./Data/color.rds')

# Read Cell Ranger output as a sparse gene-by-cell count matrix.
cortex.data <- Read10X(
  data.dir = "~/PythonScripts/Adult_cortical/Data/adult_human_cortex/AHCaggr24/filtered_feature_bc_matrix/"
)

# Create a Seurat object. Cells with fewer than 200 genes and genes detected in
# fewer than 10 cells are removed at object creation.
cortex <- CreateSeuratObject(
  counts = cortex.data,
  project = "adult_cortex",
  min.cells = 10,
  min.features = 200
)

# Load metadata produced by the Scanpy preprocessing workflow. Row names should
# correspond to Seurat cell barcodes.
metadata <- read.csv("./Data/HC_HVG2000_metadata.csv", row.names = 1)

# Add QC, sample, region, and preliminary cluster metadata to the Seurat object.
cortex <- AddMetaData(cortex, metadata = metadata)

# Calculate mitochondrial percentage in Seurat for QC visualization.
cortex[["percent.mt"]] <- PercentageFeatureSet(cortex, pattern = "^MT-")

# Inspect standard QC metrics. This plot is primarily diagnostic and is not saved
# unless the active graphics device is redirected.
VlnPlot(cortex, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)

# -----------------------------------------------------------------------------
# Step 2. Split by sample/location and integrate across samples
# -----------------------------------------------------------------------------

# Split object by `location`, which represents individual sample/location labels.
# Each subset is normalized independently before integration.
ch.list <- SplitObject(cortex, split.by = 'location')

# Normalize each sample and identify 2,000 variable features per sample.
ch.list <- lapply(ch.list, function(x) {
  x <- NormalizeData(x, verbose = FALSE)
  FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
})

# Identify integration anchors across sample/location-specific objects.
ch.anchors <- FindIntegrationAnchors(object.list = ch.list, dims = 1:30)

# Create an integrated assay that reduces sample-specific technical variation.
ch.integrated <- IntegrateData(anchorset = ch.anchors, dims = 1:30)

# -----------------------------------------------------------------------------
# Step 3. Dimensionality reduction and initial clustering
# -----------------------------------------------------------------------------

# Use integrated expression values for scaling, PCA, UMAP, and clustering.
DefaultAssay(ch.integrated) <- "integrated"

ch.integrated <- ScaleData(ch.integrated, verbose = FALSE) %>%
  RunPCA(npcs = 30, verbose = FALSE) %>%
  RunUMAP(dims = 1:30, min.dist = 0.3, reduction = "pca")

# Construct a shared-nearest-neighbor graph and cluster cells with Leiden/Louvain
# implementation used internally by Seurat's FindClusters.
ch.integrated <- FindNeighbors(ch.integrated, reduction = "pca", dims = 1:30) %>%
  FindClusters(resolution = 1)

# Visualize initial clusters for manual marker-based annotation.
DimPlot(ch.integrated, reduction = "umap", label = TRUE)

# -----------------------------------------------------------------------------
# Step 4. Excitatory neuron subsetting and annotation
# -----------------------------------------------------------------------------

# Subset clusters manually identified as excitatory neurons based on canonical
# marker genes and initial UMAP inspection.
ch.Exc <- subset(
  ch.integrated,
  idents = c('30','17','20','16','25','31','7','12','14','18','28','34','43','35','9','40','37')
)

# Recompute UMAP and clustering within the excitatory neuron compartment to
# improve resolution of excitatory subclasses.
ch.Exc <- RunUMAP(ch.Exc, dims = 1:30, min.dist = 0.3, reduction = "pca") %>%
  FindNeighbors(reduction = "pca", dims = 1:30) %>%
  FindClusters(resolution = 1)

# Plot excitatory subclusters. `gastrul_colors_37` should be defined in the
# analysis environment; alternatively replace it with `cls100`.
DimPlot(ch.Exc, reduction = "umap", label = TRUE, group.by = 'seurat_clusters', cols = gastrul_colors_37)

# Map numeric Seurat clusters to biologically interpretable excitatory neuron
# subclasses. This mapping should be based on marker genes and literature labels.
df.exc <- ch.Exc@meta.data
cluster_map <- list(
  '4' = 'L2_3_IT', '5' = 'L2_3_IT', '24' = 'L2_3_IT', '2' = 'L2_3_IT',
  '6' = 'L2_3_IT', '1' = 'L2_3_IT', '3' = 'L2_3_IT', '11' = 'L3_4_IT',
  '9' = 'L3_4_IT', '13' = 'L3_4_IT', '18' = 'L4_5_IT_1', '0' = 'L4_5_IT_1',
  '16' = 'L4_5_IT_1', '17' = 'L4_5_IT_2', '7' = 'L4_5_IT_3',
  '21' = 'L4_5_IT_3', '14' = 'L4_5_IT_3', '8' = 'L4_5_IT_3',
  '22' = 'L6_IT_1', '25' = 'L6_IT_1', '10' = 'L6_IT_1',
  '12' = 'L6_IT_2', '20' = 'L5_6_NP', '15' = 'L6_CT',
  '23' = 'L6b', '26' = 'L5_ET'
)

# Assign subclass labels to every excitatory cell.
df.exc$clusters2 <- unlist(lapply(df.exc$seurat_clusters, function(x) cluster_map[[as.character(x)]]))
ch.Exc@meta.data$clusters2 <- df.exc$clusters2

# Visualize excitatory subclass labels.
DimPlot(ch.Exc, reduction = "umap", group.by = 'clusters2', label = TRUE, cols = gastrul_colors_37)

# -----------------------------------------------------------------------------
# Step 5. Fine subclustering within each excitatory subclass
# -----------------------------------------------------------------------------

# Use the integrated assay and the previously computed SNN graph for subclustering.
DefaultAssay(ch.Exc) <- 'integrated'
subcluster_labels <- c(
  'L2_3_IT', 'L3_4_IT', 'L4_5_IT_1', 'L4_5_IT_2', 'L4_5_IT_3',
  'L6_IT_1', 'L6_IT_2', 'L5_6_NP', 'L6_CT', 'L6b', 'L5_ET'
)

# Find finer subclusters within each major excitatory subclass.
for (label in subcluster_labels) {
  ch.Exc <- FindSubCluster(
    ch.Exc,
    label,
    graph.name = 'integrated_snn',
    resolution = 0.5,
    subcluster.name = paste0(label, ".sub")
  )
}

# Visualize final excitatory subclusters and save the object.
options(repr.plot.width = 10, repr.plot.height = 10)
DimPlot(ch.Exc, group.by = 'clusters2.sub10', pt.size = 0.1, repel = TRUE, cols = cls100)
saveRDS(ch.Exc, './data/All_region_cortex_seurat_Exc.rds')

# -----------------------------------------------------------------------------
# Step 6. Combine excitatory, inhibitory, and non-neuronal annotations
# -----------------------------------------------------------------------------

# IMPORTANT:
# The inhibitory (`ch.In`) and non-neuronal (`ch.Nn`) annotation workflows should
# follow the same logic as the excitatory workflow above: subset the relevant
# initial clusters, recluster, assign subclass labels, identify fine subclusters,
# and save metadata. Those objects are required below.

# Combine metadata from excitatory, inhibitory, and non-neuronal compartments.
# The expected subcluster metadata columns are:
#   ch.Exc$clusters2.sub10 for excitatory neurons
#   ch.In$clusters2.sub9   for inhibitory neurons
#   ch.Nn$clusters2.sub5   for non-neuronal cells
clusters2_meta <- bind_rows(
  ch.Exc@meta.data %>% select(clusters2, subclusters = clusters2.sub10, class_label = 'Glutamatergic'),
  ch.In@meta.data %>% select(clusters2, subclusters = clusters2.sub9, class_label = 'GABAergic'),
  ch.Nn@meta.data %>% select(clusters2, subclusters = clusters2.sub5, class_label = 'Non_neuronal')
)

# Subset the integrated object to cells with final annotations. The object
# `ch.integrated.sub.sub` should represent the integrated object after any manual
# filtering performed during annotation.
ch.integrated.filter <- ch.integrated.sub.sub[, rownames(clusters2_meta)]
ch.integrated.filter <- AddMetaData(ch.integrated.filter, metadata = clusters2_meta)

# Visualize the final annotated object by broad subclass, fine subcluster, and
# major class label.
options(repr.plot.width = 20, repr.plot.height = 6)
DimPlot(ch.integrated.filter, group.by = 'clusters2', cols = gastrul_colors_37)
DimPlot(ch.integrated.filter, group.by = 'subclusters')
DimPlot(ch.integrated.filter, group.by = 'class_label')

# Save the final integrated and annotated Seurat object used by downstream scripts.
saveRDS(ch.integrated.filter, './data/All_region_cortex_seurat_v1.rds')
