# 1.5_integrate_region_across_species.r
#
# Purpose:
#   Integrate human and mouse excitatory neuron datasets for cross-species
#   comparison of cortical-region-associated cell subclasses. The script performs
#   reciprocal PCA integration, UMAP/clustering, cluster-label concordance
#   visualization, and cell-type proportion comparison.
#
# Inputs:
#   ./data/color.rds
#     Color palette for plotting.
#   ./data/mouse_sub_neuron.h5Seurat
#     Mouse neuronal Seurat object containing metadata such as subclass_label,
#     external_donor_name_label, and region/source annotations.
#   ./data/All_region_cortex_seurat_v1.rds
#     Human integrated Seurat object generated by 1.2_process_annotate_seurat.r.
#
# Outputs:
#   ./Figures/Human_mouse_cluster_label_corrplot_FL.pdf
#     Heatmap-like plot showing concordance between human and mouse labels.
#   ./Figures/Human_mouse_prop_FL.pdf
#     Bar plot comparing human and mouse excitatory subclass proportions.
#
# Notes:
#   The original script refers to `mouse_exc`, `cluster_level`, and metadata field
#   `source` without defining them explicitly. In this annotated version, these
#   dependencies are documented below. For direct execution, define these objects
#   or replace them with the corresponding fields in your Seurat objects.

# Load libraries for Seurat integration, data manipulation, and heatmap plotting.
library(Seurat)
library(Matrix)
library(matrixStats)
library(dplyr)
library(ggplot2)
library(SeuratDisk)
library(stringr)
library(grid)
library(pheatmap)

# Load custom color palette and define a grayscale palette for pheatmap.
cls100 <- readRDS('./data/color.rds')
heat.colors <- colorRampPalette(c("white", "grey70", "black"))(100)

# -----------------------------------------------------------------------------
# Helper function: reorder a matrix by the position of maximum values
# -----------------------------------------------------------------------------
reorder_matrix <- function(matrix1, by.rows = TRUE) {
  # If by.rows = TRUE, reorder rows according to the column index of each row's
  # maximum value. This is useful for aligning rows to their strongest matches.
  if (by.rows) {
    conf.order <- order(apply(matrix1, 1, which.max))
    matrix1.reordered <- matrix1[conf.order, ]
  } else {
    # Otherwise reorder columns according to the row index of each column's
    # maximum value.
    conf.order <- order(apply(matrix1, 2, which.max))
    matrix1.reordered <- matrix1[, conf.order]
  }
  return(matrix1.reordered)
}

# -----------------------------------------------------------------------------
# Helper function: compare cluster assignments
# -----------------------------------------------------------------------------
compare_cl <- function(cl, ref.cl, plot.title = NA, plot.silent = TRUE,
                       heat.colors = heat.colors,
                       row.cl.num = min(length(unique(cl)), length(unique(ref.cl)))) {
  # Build a contingency table between reference biological labels (`cl`) and
  # integrated clustering labels (`ref.cl`), then normalize each row to a fraction.
  conf1 <- sweep(table(cl, ref.cl), 1, rowSums(table(cl, ref.cl)), "/")

  # Reorder matrix for clearer visualization.
  conf2 <- reorder_matrix(conf1)

  # Calculate a label co-occurrence matrix. For each integrated cluster, the
  # pairwise minimum proportions across two reference labels are summed; larger
  # values indicate stronger co-assignment in integrated clusters.
  cl.prop.cocl <- apply(conf1, 2, function(x) {
    min.prop <- apply(expand.grid(x, x), 1, min)
  })

  cl.prop.cocl.total <- rowSums(cl.prop.cocl)
  cl.prop.cocl.m <- matrix(
    cl.prop.cocl.total,
    nrow(conf1),
    nrow(conf1),
    dimnames = list(rownames(conf1), rownames(conf1))
  )

  # Plot the normalized contingency matrix.
  ph1 <- pheatmap(conf2, cutree_rows = row.cl.num, clustering_method = "ward.D2",
                  color = heat.colors, fontsize = 6, main = plot.title,
                  silent = plot.silent)

  return(list(conf = conf2, cocl = cl.prop.cocl.m, ph = ph1))
}

# -----------------------------------------------------------------------------
# Helper function: plot cross-species label concordance
# -----------------------------------------------------------------------------
CorrelationPlotFun <- function(adata, human_cluster, mouse_cluster, species_cluster, integrated_cluster) {
  # Identify human and mouse cells from the species/source metadata column.
  pos.h <- grep('^human$', adata@meta.data[[species_cluster]])
  pos.m <- grep('^mouse$', adata@meta.data[[species_cluster]])

  # Prefix labels with species names to avoid collisions between human and mouse
  # labels that happen to share the same text.
  human.cluster <- paste0('human_', adata@meta.data[[human_cluster]][pos.h])
  mouse.cluster <- paste0('mouse_', adata@meta.data[[mouse_cluster]][pos.m])

  # Name vectors by cell IDs so AddMetaData aligns labels correctly.
  names(human.cluster) <- colnames(adata@assays$RNA@data)[pos.h]
  names(mouse.cluster) <- colnames(adata@assays$RNA@data)[pos.m]

  # Combine human and mouse label vectors into one metadata data frame. The column
  # is named automatically as `cluster_hm` if the vector name is set upstream; if
  # this does not happen in your R version, explicitly set colnames(cluster_hm_df).
  cluster_hm_df <- as.data.frame(c(human.cluster, mouse.cluster))
  colnames(cluster_hm_df) <- "cluster_hm"
  adata <- AddMetaData(adata, metadata = cluster_hm_df)

  # Compare original biological labels against integrated Seurat clusters.
  ref.cl <- adata$cluster_hm
  cca.cl <- adata@meta.data[[integrated_cluster]]
  names(cca.cl) <- colnames(adata@assays$RNA@data)

  cl.conf <- compare_cl(ref.cl, cca.cl)
  cocl <- cl.conf$cocl

  # Extract the human-by-mouse submatrix from the species-prefixed co-occurrence
  # matrix.
  compare.species <- unique(adata@meta.data[[species_cluster]])
  cocl.subset <- cocl[grepl(compare.species[1], row.names(cocl)),
                      grepl(compare.species[2], row.names(cocl))]

  # Remove species prefixes from row/column labels for readability.
  row.names(cocl.subset) <- sub(paste0(compare.species[1], "_"), "", row.names(cocl.subset))
  colnames(cocl.subset) <- sub(paste0(compare.species[2], "_"), "", colnames(cocl.subset))

  # Reorder and plot human-mouse label concordance.
  cocl.subset2 <- reorder_matrix(cocl.subset, by.rows = FALSE)
  pheatmap(cocl.subset2, cluster_rows = FALSE, cluster_cols = FALSE, fontsize = 6)
}

# -----------------------------------------------------------------------------
# Step 1. Load and process mouse excitatory neuron data
# -----------------------------------------------------------------------------

# Load mouse neuronal data in h5Seurat format.
mouse_neuron <- LoadH5Seurat(file = './data/mouse_sub_neuron.h5Seurat')

# Add simplified donor and cluster labels, then subset to frontal pole (FRP) and
# glutamatergic neurons. Adjust `idents` or metadata fields if your mouse object
# uses different annotation names.
mouse_neuron <- mouse_neuron %>%
  mutate(donor_label = external_donor_name_label,
         cluster_label_v1 = str_replace_all(subclass_label, "[- ]", "_")) %>%
  subset(idents = 'FRP') %>%
  subset(idents = 'Glutamatergic')

# The original code uses `mouse_exc` downstream. Here we explicitly assign it to
# the processed mouse excitatory object for clarity.
mouse_exc <- mouse_neuron

# -----------------------------------------------------------------------------
# Step 2. Load and process human frontal-lobe excitatory neurons
# -----------------------------------------------------------------------------

human_neuron <- readRDS(file = './data/All_region_cortex_seurat_v1.rds')

# Subset human frontal-lobe glutamatergic neurons, harmonize labels, create donor
# labels, and downsample human cells to match the number of mouse cells.
human_exc <- human_neuron %>%
  subset(idents = 'Frontal lobe') %>%
  subset(idents = 'Glutamatergic') %>%
  mutate(cluster_label = str_replace_all(clusters2_v1, ',', '_'),
         donor_label = paste0('H', gsub('-', '_', location))) %>%
  sample_n(size = ncol(mouse_exc))

# -----------------------------------------------------------------------------
# Step 3. Merge human and mouse data and integrate across donors/species
# -----------------------------------------------------------------------------

# Store species labels. Downstream functions refer to this information as source.
human_exc$orig.ident <- "human"
mouse_exc$orig.ident <- "mouse"
human_exc$source <- "human"
mouse_exc$source <- "mouse"

# Merge human and mouse cells into a single Seurat object.
all.data <- merge(x = human_exc, y = mouse_exc, add.cell.ids = c("human", "mouse"))

# Split by donor label so integration can account for donor/sample effects.
all.data.list <- SplitObject(all.data, split.by = "donor_label")

# Normalize each donor/sample and identify variable genes.
all.data.list <- lapply(all.data.list, function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

# Select shared integration features and run PCA in each object.
features <- SelectIntegrationFeatures(object.list = all.data.list)
all.data.list <- lapply(all.data.list, function(x) {
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})

# Find reciprocal PCA anchors and integrate the datasets.
frl_anchors <- FindIntegrationAnchors(
  object.list = all.data.list,
  anchor.features = features,
  reduction = "rpca"
)
frl_combined <- IntegrateData(anchorset = frl_anchors, k.weight = 20)

# -----------------------------------------------------------------------------
# Step 4. Dimensionality reduction, clustering, and visualization
# -----------------------------------------------------------------------------

frl_combined <- frl_combined %>%
  ScaleData(verbose = FALSE) %>%
  RunPCA(npcs = 30, verbose = FALSE) %>%
  RunUMAP(reduction = "pca", dims = 1:30) %>%
  FindNeighbors(reduction = "pca", dims = 1:30) %>%
  FindClusters(resolution = 0.5)

# Visualize integrated clusters and species-specific biological labels.
DimPlot(frl_combined, reduction = "umap", group.by = "seurat_clusters", cols = cls100)
DimPlot(frl_combined, reduction = "umap", group.by = "subclass_label", cols = cls100)
DimPlot(frl_combined, reduction = "umap", group.by = "clusters2_v1", cols = cls100)

# -----------------------------------------------------------------------------
# Step 5. Human-mouse label concordance and proportion comparison
# -----------------------------------------------------------------------------

# Create and save a concordance plot between human clusters and mouse subclasses.
p <- CorrelationPlotFun(frl_combined, 'clusters2_v1', 'subclass_label', 'source', 'seurat_clusters')
pdf("./Figures/Human_mouse_cluster_label_corrplot_FL.pdf", width = 8, height = 10)
print(p)
dev.off()

# Define the expected order of excitatory labels in the proportion plot. Modify
# this vector if additional subclasses are present.
cluster_level <- c(
  'L2_3_IT', 'L3_4_IT', 'L4_5_IT_1', 'L4_5_IT_2', 'L4_5_IT_3',
  'L6_IT_1', 'L6_IT_2', 'L5_6_NP', 'L5_ET', 'L6_CT', 'L6b'
)

# For each cell, use human cluster labels for human cells and mouse subclass
# labels for mouse cells, then calculate within-donor proportions.
df <- frl_combined@meta.data %>%
  mutate(cluster_comb = ifelse(source == 'human', clusters2_v1, subclass_label),
         cluster_comb_v1 = factor(cluster_comb, levels = cluster_level))

g.exc <- df %>%
  count(source, donor_label, cluster_comb_v1) %>%
  group_by(source, donor_label) %>%
  mutate(freq = n / sum(n)) %>%
  ggplot(aes(x = cluster_comb_v1, y = freq, color = source, fill = source)) +
  stat_summary(fun.data = mean_se, position = position_dodge(0.75), geom = "errorbar", width = 0.5) +
  stat_summary(fun = mean, position = position_dodge(0.75), geom = "bar", width = 0.65) +
  xlab("") + ylab("Cell type proportion in brain regions") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))

plot(g.exc)
ggsave(g.exc, file = "./Figures/Human_mouse_prop_FL.pdf", width = 7.5, height = 5)
