"""
1.7_GWAS_1.py

Purpose
-------
Prepare cell-type specificity scores for downstream CELLECT-MAGMA analysis. The
script uses CELLEX to calculate expression specificity statistics for each
region-by-cell-subclass label, such as `Frontal lobe_L2_3_IT`.

Main input
----------
- ./data/All_region_cortex_raw.h5ad
  Raw or normalized AnnData object containing expression matrix, gene IDs, and
  cell metadata. Required obs columns: MainLoc and clusters2_v1. Required var
  column: gene_ids.

Main output
-----------
- ./data/MainLoc_clusters2_v1_human_brain_cells*.csv
  CELLEX specificity result files used as input for CELLECT-MAGMA.
"""

# Scanpy is used for reading AnnData and setting plot parameters.
import scanpy as sc

# Pandas is used to convert the AnnData expression matrix into a gene-by-cell
# DataFrame required by CELLEX.
import pandas as pd

# CELLEX calculates cell-type expression specificity statistics.
import cellex

# Set figure parameters for any diagnostic plots generated by Scanpy.
sc.settings.set_figure_params(dpi=120)

# -----------------------------------------------------------------------------
# Step 1. Load AnnData object
# -----------------------------------------------------------------------------

# Load the adult human cortex AnnData object. The object should include:
# - adata_raw.X: expression matrix with cells as rows and genes as columns
# - adata_raw.obs['MainLoc']: anatomical region labels
# - adata_raw.obs['clusters2_v1']: cell subclass labels
# - adata_raw.var['gene_ids']: stable gene identifiers used as row names
adata_raw = sc.read('./data/All_region_cortex_raw.h5ad')

# -----------------------------------------------------------------------------
# Step 2. Create region-by-cell-subclass labels
# -----------------------------------------------------------------------------

# Combine anatomical region and cell subclass into one annotation label. This
# allows CELLEX and CELLECT-MAGMA to test specificity for each region-specific
# cell subclass rather than for broad classes only.
adata_raw.obs['MainLoc_clusters2_v1'] = (
    adata_raw.obs['MainLoc'] + '_' + adata_raw.obs['clusters2_v1']
)

# -----------------------------------------------------------------------------
# Step 3. Prepare CELLEX input matrix and metadata
# -----------------------------------------------------------------------------

# CELLEX expects a gene-by-cell expression matrix. AnnData stores cells-by-genes,
# so the matrix is transposed. Gene IDs are used as row names, and cell barcodes
# are used as columns.
data = pd.DataFrame(
    adata_raw.X.T,
    index=adata_raw.var['gene_ids'],
    columns=adata_raw.obs_names
)

# Extract the annotation vector used to group cells for specificity analysis.
metadata = adata_raw.obs['MainLoc_clusters2_v1']

# -----------------------------------------------------------------------------
# Step 4. Run CELLEX expression specificity analysis
# -----------------------------------------------------------------------------

# Create the CELLEX ESObject. The expression matrix and annotation vector must
# contain the same cells in the same order.
eso = cellex.ESObject(data=data, annotation=metadata, verbose=True)

# Compute expression specificity statistics for each gene and annotation label.
eso.compute(verbose=True)

# Print the first rows of the ESMu specificity table for a quick sanity check.
print(eso.results["esmu"].head())

# Save CELLEX result files. These files are used by the CELLECT-MAGMA pipeline.
eso.save_as_csv(
    path='./data/',
    file_prefix='MainLoc_clusters2_v1_human_brain_cells',
    verbose=True
)
